version: '3.9'
services:
  mongo:
    container_name: notifications_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - auth

networks:
  auth:
