version: '3.9'
services:
  mongo:
    container_name: notifications-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - notifications

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: notifications-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #    volumes:
    #      - ./kafka/zookeeper/data:/var/lib/zookeeper/data
    #      - ./kafka/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - 22181:2181
    networks:
      - notifications

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: notifications-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.0.235:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #    volumes:
      #      - ./kafka/broker/data:/var/lib/kafka/data
    networks:
      - notifications
  mailhog:
    image: mailhog/mailhog
    container_name: notifications-mailhog
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - notifications


networks:
  notifications:
