spring:
  application:
    name: notification-service

server:
  port: 9001

kafka:
  consumer-number: 1
  securityProtocol: SASL_SSL
  saslMechanism: SCRAM-SHA-512
  max-poll-records: 10000
  max-poll-interval-ms: 30000
  request-timeout-ms: 11000
  connections-max-idle-ms: 240000
  poll-timeout-ms: 1000
  auto-offset-reset: earliest
  ssl:
    enabled: false
  retry:
    max-retries: 5
    back-off-period: 500
    backoff-period-service-unavailable: 5000
  retry-backoff-ms: 1000

notifications:
  store-in-database: true
  auth-enabled: true
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    auth: false
    starttls-enable: false
    debug: true
    test-connection: false



eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true


management:
  health:
    defaults:
      enabled: false
    mongo:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "health,info"
logging:
  logback:
    rollingpolicy:
      max-history: 5
    compression-type: zip

