spring:
  application:
    name: notification-service
  profiles:
    active: dev
#  datasource:
#    username: root
#    password: password
#    url: jdbc:postgresql://localhost:5432/dams_db

server:
  port: 9001


mail:
  host: localhost
  port: 1025
  protocol: smtp
  auth: false
  starttls-enable: false
  debug: true
  test-connection: false


kafka:
  bootstrap-servers: localhost:9092
  consumer-number: 1
  auto-offset-reset: earliest
  max-poll-interval: 30000
  max-poll-records: 1
  poll-timeout-ms: 1000
  retry-backoff-in-ms: 100
  request-timeout-ms: 11000
  connections-max-idle-ms: 240000
  ssl:
    enabled: false
  application-id: notification-service
  topics:
    sms: sms
