spring:
  application:
    name: notification-service
#  datasource:
#    username: root
#    password: password
#    url: jdbc:postgresql://localhost:5432/dams_db

server:
  port: 9001


mail:
  host: localhost
  port: 1025
  protocol: smtp
  auth: false
  starttls-enable: false
  debug: true
  test-connection: false


kafka:
  consumer-number: 1
  securityProtocol: SASL_SSL
  saslMechanism: SCRAM-SHA-512
  max-poll-records: 10000
  max-poll-interval: 30000
  request-timeout-ms: 11000
  connections-max-idle-ms: 240000
  poll-timeout-ms: 1000
  ssl:
    enabled: false
  retry:
    max-retries: 5
    back-off-period: 500
    backoff-period-service-unavailable: 5000

